package Vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.time.LocalDate;
import javax.swing.JPanel;

public class Dashboard extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    Connection reg;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();

        
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
 
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btn_reserva = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_habitacion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_productos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_servicios = new javax.swing.JPanel();
        btn_usuarios = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_huespedes = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        app_name = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Title = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reserva.setBackground(new java.awt.Color(21, 101, 192));
        btn_reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reservaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_reservaMousePressed(evt);
            }
        });
        btn_reserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reservas");
        btn_reserva.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 270, 50));

        btn_habitacion.setBackground(new java.awt.Color(18, 90, 173));
        btn_habitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_habitacion.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_habitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_habitacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_habitacionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_habitacionMousePressed(evt);
            }
        });
        btn_habitacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Habitaciones");
        btn_habitacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        btn_productos.setBackground(new java.awt.Color(18, 90, 173));
        btn_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_productos.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_productosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_productosMousePressed(evt);
            }
        });
        btn_productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Productos");
        btn_productos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 50));

        btn_servicios.setBackground(new java.awt.Color(18, 90, 173));
        btn_servicios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_servicios.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_serviciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_serviciosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_serviciosMousePressed(evt);
            }
        });
        btn_servicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_usuarios.setBackground(new java.awt.Color(18, 90, 173));
        btn_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_usuarios.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_usuariosMousePressed(evt);
            }
        });
        btn_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuarios");
        btn_usuarios.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btn_servicios.add(btn_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.add(btn_servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 50));

        btn_huespedes.setBackground(new java.awt.Color(18, 90, 173));
        btn_huespedes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_huespedes.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_huespedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_huespedesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_huespedesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_huespedesMousePressed(evt);
            }
        });
        btn_huespedes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Huespedes");
        btn_huespedes.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_huespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setText("VALQUIRIA");
        Menu.add(app_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 190, 20));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 640));

        Header.setBackground(new java.awt.Color(25, 118, 210));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recepcion/Control/Reservas");

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Hoy es Sábado 28 de Abril de 2018");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(fecha))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 750, 150));

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleMouseDragged(evt);
            }
        });
        Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleMousePressed(evt);
            }
        });

        red_squr.setBackground(new java.awt.Color(255, 255, 255));
        red_squr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        red_squr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                red_squrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                red_squrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                red_squrMousePressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 102, 102));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addGap(0, 984, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(red_squr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        slogan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slogan.setText("Vive tus sueños en nuestro Hotel de ensueño");
        Background.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 300, 30));

        content.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 430));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setText("Bienvenido");
        jPanel1.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Sistema de Gestión de Reservas para el Hotel Valquiria. Controle y administre de");
        jPanel1.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("forma óptima y fácil el flujo de reservas y servicios de Libros. ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Esta herramienta le permitirá llevar un control completo y detallado de la Recepcion,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("tendrá acceso a herramientas especiales para tareas específicas, como lo son:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("• Sección de Reportes de acciones en el sistema");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 330, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("• Reservas");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("• Check-in y Check-out");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("• Registro de Clientes");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 320, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("• Edición de Usuarios y Libros existentes");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 330, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("• Eliminar todo tipo de Registros");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 330, -1));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 750, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void TitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_TitleMouseDragged

    private void TitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TitleMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void btn_reservaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservaMousePressed
        setColor(btn_reserva);
        resetColor(btn_huespedes);
        resetColor(btn_habitacion);
        resetColor(btn_productos);
        resetColor(btn_servicios);
        resetColor(btn_usuarios);
        // Abrir sección
        FrmReservaVista newframe = new FrmReservaVista();
        newframe.setVisible(true);
    }//GEN-LAST:event_btn_reservaMousePressed

    private void btn_huespedesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_huespedesMousePressed
        resetColor(btn_reserva);
        setColor(btn_huespedes);
        resetColor(btn_habitacion);
        resetColor(btn_productos);
        resetColor(btn_servicios);
        resetColor(btn_usuarios);
        // Abrir sección
        FrmClienteVista newframe = new FrmClienteVista();
        newframe.setVisible(true);
    }//GEN-LAST:event_btn_huespedesMousePressed

    private void btn_habitacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_habitacionMousePressed
        resetColor(btn_reserva);
        resetColor(btn_huespedes);
        setColor(btn_habitacion);
        resetColor(btn_productos);
        resetColor(btn_servicios);
        resetColor(btn_usuarios);
        // Abrir sección
        FrmHabitacionVista newframe = new FrmHabitacionVista();
        newframe.setVisible(true);
    }//GEN-LAST:event_btn_habitacionMousePressed

    private void btn_productosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMousePressed
        resetColor(btn_reserva);
        resetColor(btn_huespedes);
        resetColor(btn_habitacion);
        setColor(btn_productos);
        resetColor(btn_servicios);
        resetColor(btn_usuarios);
        // Abrir sección
        FrmProductoVista newframe = new FrmProductoVista();
        newframe.setVisible(true);
    }//GEN-LAST:event_btn_productosMousePressed

    private void btn_serviciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_serviciosMousePressed
      
    }//GEN-LAST:event_btn_serviciosMousePressed

    private void btn_usuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMousePressed
        resetColor(btn_reserva);
        resetColor(btn_huespedes);
        resetColor(btn_habitacion);
        resetColor(btn_productos);
        resetColor(btn_servicios);
        // Abrir sección
        FrmUsuarioVista newframe = new FrmUsuarioVista();
        newframe.setVisible(true);
        
    }//GEN-LAST:event_btn_usuariosMousePressed

    private void red_squrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMousePressed
        System.exit(0);
    }//GEN-LAST:event_red_squrMousePressed

    private void btn_huespedesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_huespedesMouseEntered
        if(btn_huespedes.getBackground().getRGB() == -15574355)
            setColor(btn_huespedes);
    }//GEN-LAST:event_btn_huespedesMouseEntered

    private void btn_huespedesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_huespedesMouseExited
        if(btn_reserva.getBackground().getRGB() != -15574355 || btn_habitacion.getBackground().getRGB() != -15574355
            || btn_productos.getBackground().getRGB() != -15574355 || btn_servicios.getBackground().getRGB() != -15574355 || btn_usuarios.getBackground().getRGB() != -15574355)
            resetColor(btn_huespedes);
    }//GEN-LAST:event_btn_huespedesMouseExited

    private void btn_reservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservaMouseEntered
        if(btn_reserva.getBackground().getRGB() == -15574355)
            setColor(btn_reserva);
    }//GEN-LAST:event_btn_reservaMouseEntered

    private void btn_reservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reservaMouseExited
        if(btn_huespedes.getBackground().getRGB() != -15574355 || btn_habitacion.getBackground().getRGB() != -15574355
            || btn_productos.getBackground().getRGB() != -15574355 || btn_servicios.getBackground().getRGB() != -15574355 || btn_usuarios.getBackground().getRGB() != -15574355)
            resetColor(btn_reserva);
    }//GEN-LAST:event_btn_reservaMouseExited

    private void btn_habitacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_habitacionMouseEntered
        if(btn_habitacion.getBackground().getRGB() == -15574355)
            setColor(btn_habitacion);
    }//GEN-LAST:event_btn_habitacionMouseEntered

    private void btn_habitacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_habitacionMouseExited
        if(btn_huespedes.getBackground().getRGB() != -15574355 || btn_reserva.getBackground().getRGB() != -15574355
            || btn_productos.getBackground().getRGB() != -15574355 || btn_servicios.getBackground().getRGB() != -15574355 || btn_usuarios.getBackground().getRGB() != -15574355)
            resetColor(btn_habitacion);
    }//GEN-LAST:event_btn_habitacionMouseExited

    private void btn_productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMouseEntered
        if(btn_productos.getBackground().getRGB() == -15574355)
            setColor(btn_productos);
    }//GEN-LAST:event_btn_productosMouseEntered

    private void btn_productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMouseExited
        if(btn_huespedes.getBackground().getRGB() != -15574355 || btn_reserva.getBackground().getRGB() != -15574355
            || btn_habitacion.getBackground().getRGB() != -15574355 || btn_servicios.getBackground().getRGB() != -15574355 || btn_usuarios.getBackground().getRGB() != -15574355)
            resetColor(btn_productos);
    }//GEN-LAST:event_btn_productosMouseExited

    private void btn_serviciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_serviciosMouseEntered
        if(btn_servicios.getBackground().getRGB() == -15574355)
            setColor(btn_servicios);
    }//GEN-LAST:event_btn_serviciosMouseEntered

    private void btn_serviciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_serviciosMouseExited
        if(btn_huespedes.getBackground().getRGB() != -15574355 || btn_reserva.getBackground().getRGB() != -15574355
            || btn_habitacion.getBackground().getRGB() != -15574355 || btn_productos.getBackground().getRGB() != -15574355 || btn_usuarios.getBackground().getRGB() != -15574355)
            resetColor(btn_servicios);
    }//GEN-LAST:event_btn_serviciosMouseExited

    private void btn_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseEntered
        if(btn_usuarios.getBackground().getRGB() == -15574355)
            setColor(btn_usuarios);
    }//GEN-LAST:event_btn_usuariosMouseEntered

    private void btn_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseExited
        if(btn_huespedes.getBackground().getRGB() != -15574355 || btn_reserva.getBackground().getRGB() != -15574355
            || btn_habitacion.getBackground().getRGB() != -15574355 || btn_productos.getBackground().getRGB() != -15574355 || btn_servicios.getBackground().getRGB() != -15574355)
            resetColor(btn_usuarios);
    }//GEN-LAST:event_btn_usuariosMouseExited

    private void red_squrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_red_squrMouseEntered

    private void red_squrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_red_squrMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_exitMouseExited

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Text1;
    private javax.swing.JPanel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel app_name;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btn_habitacion;
    private javax.swing.JPanel btn_huespedes;
    private javax.swing.JPanel btn_productos;
    private javax.swing.JPanel btn_reserva;
    private javax.swing.JPanel btn_servicios;
    private javax.swing.JPanel btn_usuarios;
    public static javax.swing.JPanel content;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel red_squr;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}
